@hostname = localhost
@port = 5041
@host = http://{{hostname}}:{{port}}
@contentType = application/json

###

# @name login
# Captures the response payload so we can extract the token for protected routes
POST {{host}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "candidate3@example.com",
  "password": "Password123!"
}

###

# This variable grabs the accessToken from the JSON returned 
@authToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}

###

POST {{host}}/api/auth/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "{{refreshToken}}"
}

###


POST {{host}}/api/topics
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
  "name": "C# Programming"
}

###


POST {{host}}/api/topics
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
  "name": "SQL"
}

###


POST {{host}}/api/topics
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
  "name": "NoSQL"
}

###


POST {{host}}/api/topics
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
  "name": "Entity Framework"
}

###

GET {{host}}/api/topics
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}
